matrix:
  include:
    - language: node_js
      dist: bionic
      node_js:
        - 8
      before_install:
        - npm i -g npm@version-number
      before_script:
        - cd whos-got-next-backend
        - npm install
      script: npm test
