matrix:
  include:
    - language: node_js
      dist: bionic
      node_js:
        - 8
      before_install:
        - npm i -g npm@version-number
      before_script:
        - cd whos-got-next-backend
        - npm install
      script: npm run test

    - os: osx
      language: objective-c
      osx_image: xcode9.4
      env:
        - JOB_NAME=IOS
      before_install:
        - npm i -g npm@version-number
      before_script:
        - cd NEWEST-FRONTEND
        - npm install
      script: # ios test command

    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-26.0.3
          - android-21
          - android-26
          - sys-img-armeabi-v7a-android-21
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      env:
        - JOB_NAME=ANDROID
      before_install:
        - npm i -g npm@version-number
      before_script:
        - cd NEWEST-FRONTEND
        - npm install
      script: # android test command
